FROM fedora:latest

RUN dnf install -y python3 python3-pip && dnf clean all

WORKDIR /code

COPY requirements.txt /code/

RUN pip install --no-cache-dir -r requirements.txt

CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]